version: '3.8'

services:
  app:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: ["npm", "start"]
    environment:
      - NODE_ENV=development
